# Change these first
owner: lazyyz # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: fxtalk
    url: https://fxtalk.cn
  - name: LOVE
    url: https://love.fxtalk.cn
  - name: Fun
    url: https://fun.fxtalk.cn
  - name: CIHU
    url: https://www.cihucm.com
  - name: SP
    url: https://www.shenpei.net
  - name: YQ
    url: https://www.yqjf68.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.fxtalk.cn
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "Uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: fxtalk.cn
      href: https://fxtalk.cn

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
